#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    url: jdbc:postgresql://localhost:5432/sport
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create